In [34]:
#Entrega 3 Miguel Chaveinte

In [35]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import accuracy_score
from scipy.stats import mode

In [36]:
#Leemos el dataset
data = pd.read_csv("C:/Users/migue/OneDrive/Escritorio/MINERIA/python-teodoro/practica1/seeds_dataset.txt", sep="\t")

In [37]:
data.head()

A      P       C    Len    Wid    Asy   Len2  Wheat
0  15.26  14.84  0.8710  5.763  3.312  2.221  5.220      1
1  14.88  14.57  0.8811  5.554  3.333  1.018  4.956      1
2  14.29  14.09  0.9050  5.291  3.337  2.699  4.825      1
3  13.84  13.94  0.8955  5.324  3.379  2.259  4.805      1
4  16.14  14.99  0.9034  5.658  3.562  1.355  5.175      1

In [38]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       210 non-null    float64
 1   P       210 non-null    float64
 2   C       210 non-null    float64
 3   Len     210 non-null    float64
 4   Wid     210 non-null    float64
 5   Asy     210 non-null    float64
 6   Len2    210 non-null    float64
 7   Wheat   210 non-null    int64  
dtypes: float64(7), int64(1)
memory usage: 13.2 KB


In [39]:
data.columns

Index(['A', 'P', 'C', 'Len', 'Wid', 'Asy', 'Len2', 'Wheat'], dtype='object')

In [40]:
#Separamos variable objetivo y estandarizamos datos
y=data.Wheat
y=np.array(y)
X = StandardScaler().fit_transform(data.iloc[:,:-1])
print(np.unique(y))
print('-----')
print(X)

[1 2 3]
-----
[[ 1.42097769e-01  2.15462437e-01  6.06017918e-05 ...  1.41701823e-01
  -9.86151745e-01 -3.83577423e-01]
 [ 1.11880257e-02  8.22375713e-03  4.28515270e-01 ...  1.97432229e-01
  -1.78816620e+00 -9.22013487e-01]
 [-1.92066576e-01 -3.60200562e-01  1.44238325e+00 ...  2.08047544e-01
  -6.67479334e-01 -1.18919199e+00]
 ...
 [-5.67570840e-01 -6.90247348e-01  7.33948301e-01 ... -7.06044846e-02
   3.07658816e+00 -7.18060432e-01]
 [-1.03608992e+00 -1.03564515e+00 -8.01701104e-01 ... -1.12152071e+00
  -6.81351965e-02 -7.42534799e-01]
 [-8.77620233e-01 -9.35863561e-01 -1.10234659e-01 ... -7.55292327e-01
   1.29122264e+00 -7.03783718e-01]]


In [41]:
df_describe = pd.DataFrame(X)
df_describe.describe()

0             1             2             3             4  \
count  2.100000e+02  2.100000e+02  2.100000e+02  2.100000e+02  2.100000e+02   
mean  -5.392512e-17  9.146123e-17  1.322091e-15 -2.182910e-15 -2.030122e-16   
std    1.002389e+00  1.002389e+00  1.002389e+00  1.002389e+00  1.002389e+00   
min   -1.466714e+00 -1.649686e+00 -2.668236e+00 -1.650501e+00 -1.668209e+00   
25%   -8.879552e-01 -8.514330e-01 -5.980791e-01 -8.286816e-01 -8.349072e-01   
50%   -1.696741e-01 -1.836639e-01  1.039927e-01 -2.376280e-01 -5.733534e-02   
75%    8.465989e-01  8.870693e-01  7.116771e-01  7.945947e-01  8.044956e-01   
max    2.181534e+00  2.065260e+00  2.006586e+00  2.367533e+00  2.055112e+00   

                  5             6  
count  2.100000e+02  2.100000e+02  
mean  -3.679596e-16 -1.337554e-16  
std    1.002389e+00  1.002389e+00  
min   -1.956769e+00 -1.813288e+00  
25%   -7.591477e-01 -7.404953e-01  
50%   -6.746852e-02 -3.774588e-01  
75%    7.123789e-01  9.563941e-01  
max    3.170590e+00  2.328998e+00

In [42]:
X.shape,y.shape

((210, 7), (210,))

### **KMeans --> AgglomerativeClustering con 12 baricentros**

In [43]:
# En clase hemos expuesto que el número minimo de clusters es 6
min_clusters = 6
max_clusters = 12

# Creamos el rango de clusters
rango = list(range(min_clusters,max_clusters+1))

# Indices de la lista --> i for i in range(6,13)
lista = [6,7,8,9,10,11,12]

# Creamos el DataFrame, con el tamaño adecuado
tabla = pd.DataFrame(columns=["ward"], index=rango, data=np.zeros((len(lista),1)))

# n_clusters es el número de clusters, que es el indice de la tabla
tabla.index.name = "n_clusters"
tabla

ward
n_clusters      
6            0.0
7            0.0
8            0.0
9            0.0
10           0.0
11           0.0
12           0.0

In [44]:
for k in rango:
    # AgglomerativeClustering usando Linkage = Ward 
    clustering = AgglomerativeClustering(n_clusters=k, linkage="ward")
    # Entrenamos y predecimos
    clustering.fit_predict(X)
    moda=-1 * np.ones(int(k),dtype='int') #moda por cada cluster
    for i in range(int(k)):
         moda[i] = mode(y[np.argwhere(clustering.labels_== i)],keepdims=False)[0].astype(int) #vemos clase mayoritaria en cada cluster // En colab no hace falta: keepdims=False
    y_test_predict = moda[clustering.labels_]  #clases asociadas por la moda en cada cluster predicho
    tabla.loc[k,"ward"] = accuracy_score(y, y_test_predict) #comprobamos el accuracy de la real a la predicha
tabla

ward
n_clusters          
6           0.928571
7           0.928571
8           0.928571
9           0.928571
10          0.928571
11          0.928571
12          0.928571

### **Kmedoids --> 12 clusters, usando PAM, y centros con k-meoid++**

In [45]:
!pip install scikit-learn-extra

In [46]:
# Primero he instalado el paquete sklearn_extra y ahora importo KMedoids
from sklearn_extra.cluster import KMedoids

In [47]:
# En clase hemos expuesto que el número minimo de clusters es 6
min_clusters = 1
max_clusters = 12

# Creamos el rango de clusters
rango = list(range(min_clusters,max_clusters+1))

# Indices de la lista --> i for i in range(6,13)
lista = list(range(1,13))

# Creamos el DataFrame, con el tamaño adecuado
tabla = pd.DataFrame(columns=["PAM"], index=rango, data=np.zeros((len(lista),1)))

# n_clusters es el número de clusters, que es el indice de la tabla
tabla.index.name = "n_clusters"
tabla

PAM
n_clusters     
1           0.0
2           0.0
3           0.0
4           0.0
5           0.0
6           0.0
7           0.0
8           0.0
9           0.0
10          0.0
11          0.0
12          0.0

In [48]:
for k in rango:
    # AgglomerativeClustering usando Linkage = Ward 
    clustering = KMedoids(n_clusters=k,init="k-medoids++").fit(X)
    moda=-1 * np.ones(int(k),dtype='int') #moda por cada cluster
    for i in range(int(k)):
         moda[i] = mode(y[np.argwhere(clustering.labels_== i)],keepdims=False)[0].astype(int) #vemos clase mayoritaria en cada cluster // En colab no hace falta: keepdims=False
    y_test_predict = moda[clustering.labels_]  #clases asociadas por la moda en cada cluster predicho
    tabla.loc[k,"PAM"] = accuracy_score(y, y_test_predict) #comprobamos el accuracy de la real a la predicha
tabla

PAM
n_clusters          
1           0.333333
2           0.657143
3           0.909524
4           0.900000
5           0.904762
6           0.866667
7           0.904762
8           0.861905
9           0.885714
10          0.904762
11          0.880952
12          0.871429

In [49]:
clustering.labels_

array([ 2,  2, 11, 11,  2,  2,  2,  2,  9,  9,  9,  2,  2,  2,  2,  2, 11,
        2, 11,  7,  2,  2,  2,  7,  2,  9,  7,  1,  2,  1,  2,  9,  1,  2,
        2,  9,  9,  9,  2,  6,  2,  2, 11,  9,  2,  2,  2,  2,  2,  2,  2,
        0,  1,  2,  9,  9,  2,  2,  2,  1,  7,  7,  7,  6, 11, 11,  2,  2,
        2,  1,  3,  3,  3, 10,  3,  3,  3,  5,  5,  9,  0,  0,  5,  5,  5,
       10, 10,  5,  5,  5,  5, 10, 10,  0,  3,  3,  5,  5,  3, 10,  9, 10,
       10,  5,  5, 10, 10,  3,  5, 10, 10,  5, 10,  3,  5,  5, 10,  5, 10,
        5,  5,  3,  9, 10,  2, 10,  3, 10,  5,  0, 10, 10,  9,  9,  0,  2,
        3,  9,  9,  9,  6,  6,  6,  6,  4,  4,  1,  6,  1,  4,  6,  4,  1,
        4,  4,  4,  7,  4,  4,  4,  1,  6,  6,  6,  8,  7,  6,  1,  4,  4,
        4,  8,  4,  4,  4,  6,  4,  4,  6,  1,  6,  6,  6,  6,  6,  4,  4,
        4,  8,  6,  4,  6,  7,  4,  6,  7,  6,  7,  1, 11,  6, 11,  7,  8,
        6,  7,  6,  8,  1,  6], dtype=int64)

### **DBScan, con valor Eps, y minimo de muestras entorno a 12 clusters antes de eliminar puntos aislados**

In [50]:
from sklearn.cluster import DBSCAN

In [51]:
clustering = DBSCAN(eps=0.70, min_samples=2).fit(X)
clusters = clustering.labels_
np.unique(clusters)

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64)

In [52]:
#TRAS HABLAR CON TEODORO, ES ASÍ:

In [53]:
k=np.max(clusters)+1  # 

moda=-1 * np.ones(int(k),dtype='int') #moda por cada cluster
for i in range(int(k)):
      moda[i] = mode(y[np.argwhere(clusters== i)],keepdims=False)[0].astype(int) #vemos clase mayoritaria en cada cluster // En colab no hace falta: keepdims=False
y_test_predict = moda[clusters]  #clases asociadas por la moda en cada cluster predicho
print(" El acierto es de:" ,accuracy_score(y, y_test_predict)) #comprobamos el accuracy de la real a la predicha

 El acierto es de: 0.6238095238095238


In [54]:
#fin

In [55]:
no_clasificados = clusters[(clusters == -1)]
pd.value_counts(no_clasificados)

-1    40
dtype: int64

In [56]:
# Nos quedamos con los datos X que si que consigue clasificar es decir labels_ != -1 
indices = []
for i in range(len(clusters)):
    if(clusters[i] != -1):
        indices.append(i)
# Indices de las instancias que si que conseguimos clasificar
print(indices)

[0, 1, 2, 3, 4, 5, 6, 7, 11, 13, 14, 17, 19, 20, 21, 22, 24, 26, 28, 29, 32, 33, 34, 38, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 52, 53, 54, 55, 56, 57, 58, 62, 63, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 80, 81, 82, 83, 84, 85, 86, 88, 89, 90, 91, 92, 93, 95, 96, 99, 101, 102, 103, 104, 105, 106, 107, 109, 110, 111, 112, 115, 116, 117, 118, 119, 120, 121, 122, 123, 125, 126, 127, 128, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 142, 143, 144, 145, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 180, 181, 182, 183, 184, 185, 186, 187, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209]


In [57]:
data_clean=data.iloc[[elemento for elemento in indices]]
data_clean

A      P       C    Len    Wid    Asy   Len2  Wheat
0    15.26  14.84  0.8710  5.763  3.312  2.221  5.220      1
1    14.88  14.57  0.8811  5.554  3.333  1.018  4.956      1
2    14.29  14.09  0.9050  5.291  3.337  2.699  4.825      1
3    13.84  13.94  0.8955  5.324  3.379  2.259  4.805      1
4    16.14  14.99  0.9034  5.658  3.562  1.355  5.175      1
..     ...    ...     ...    ...    ...    ...    ...    ...
205  12.19  13.20  0.8783  5.137  2.981  3.631  4.870      3
206  11.23  12.88  0.8511  5.140  2.795  4.325  5.003      3
207  13.20  13.66  0.8883  5.236  3.232  8.315  5.056      3
208  11.84  13.21  0.8521  5.175  2.836  3.598  5.044      3
209  12.30  13.34  0.8684  5.243  2.974  5.637  5.063      3

[170 rows x 8 columns]

In [58]:
data_clean.index=(list(range(0,len(indices))))

In [59]:
data_clean


A      P       C    Len    Wid    Asy   Len2  Wheat
0    15.26  14.84  0.8710  5.763  3.312  2.221  5.220      1
1    14.88  14.57  0.8811  5.554  3.333  1.018  4.956      1
2    14.29  14.09  0.9050  5.291  3.337  2.699  4.825      1
3    13.84  13.94  0.8955  5.324  3.379  2.259  4.805      1
4    16.14  14.99  0.9034  5.658  3.562  1.355  5.175      1
..     ...    ...     ...    ...    ...    ...    ...    ...
165  12.19  13.20  0.8783  5.137  2.981  3.631  4.870      3
166  11.23  12.88  0.8511  5.140  2.795  4.325  5.003      3
167  13.20  13.66  0.8883  5.236  3.232  8.315  5.056      3
168  11.84  13.21  0.8521  5.175  2.836  3.598  5.044      3
169  12.30  13.34  0.8684  5.243  2.974  5.637  5.063      3

[170 rows x 8 columns]

In [60]:
X = data_clean
y=data_clean.Wheat
y=np.array(y)
X = StandardScaler().fit_transform(X)
X.shape

(170, 8)

In [61]:
data_clean.columns

Index(['A', 'P', 'C', 'Len', 'Wid', 'Asy', 'Len2', 'Wheat'], dtype='object')

In [62]:
clustering.fit(X)
new_clusters = clustering.labels_
new_clusters

array([ 0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  1,  0,
        0,  0,  0,  2,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,
        2,  0,  0,  0,  0,  1,  0, -1,  0, -1,  0,  0,  0, -1,  3,  3,  3,
        4,  3,  3,  3,  5,  6,  7,  8,  4,  4, -1,  9,  9,  8,  4,  4,  6,
        3,  4,  4,  4,  4,  4,  4,  4,  4,  3,  4,  4, -1, -1,  4,  4,  4,
        4,  4,  7,  3,  3,  4,  4,  3,  4,  8,  4,  4,  3,  3,  5, -1,  3,
       10, 10,  3, 11, 12, 11, 11, 11, 11, 11, 11, 11, -1, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 11, 11, 11, 11, 11, 11, 13,
       11, 11, 11, 11, 11, 11, 14, 11, 14, 11, 15, 11, 13, 11, 15, 11, 11],
      dtype=int64)

In [63]:
np.unique(new_clusters)

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
      dtype=int64)

In [64]:
k=np.max(new_clusters)+1  # 

moda=-1 * np.ones(int(k),dtype='int') #moda por cada cluster
for i in range(int(k)):
      moda[i] = mode(y[np.argwhere(new_clusters== i)],keepdims=False)[0].astype(int) #vemos clase mayoritaria en cada cluster // En colab no hace falta: keepdims=False
y_test_predict = moda[new_clusters]  #clases asociadas por la moda en cada cluster predicho
print(" El acierto es de:" ,accuracy_score(y, y_test_predict)) #comprobamos el accuracy de la real a la predicha

 El acierto es de: 0.9529411764705882
